spring.application.name=RV

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/result_viewer
spring.datasource.username=root
spring.datasource.password=Rohit#66
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.security.user.name=User
spring.security.user.password=rohit